import math

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 120

ROTATION_VELOCITY = 250
ACCELERATION = 3125
MAX_VELOCITY = 625
BRAKE_FORCE = 0.9

MAX_DURATION = 10

DIAGONAL = math.sqrt(SCREEN_WIDTH * SCREEN_WIDTH + SCREEN_HEIGHT * SCREEN_HEIGHT)
STAR_COLORS = ["#f2dfaa", "#ddb1f0", "#c3c2f2", "#f2b8c1", "#b5f2f7", "#ffffff", "#ffffff", "#ffffff", "#ffffff"]
