import math

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

FPS = 120

ROTATION_VELOCITY = 250
ACCELERATION = 3125
MAX_VELOCITY = 625
BRAKE_FORCE = .9

DIAGONAL = math.sqrt(SCREEN_WIDTH * SCREEN_WIDTH + SCREEN_HEIGHT + SCREEN_HEIGHT)
